### ISSUE TITLE
Add test cases for the current functionality.

### ISSUE THREAD

**Issue by horw** [bugen/pypipe#11]
What do you think about adding tests for the current functionality? 
If this repository will be adding more features, maybe it's better to include them because someone's PR can break something else. 
I can help you add these basic tests if you agree.

**Comment by bugen** [comment]
I also believe that tests are necessary.

> I can help you add these basic tests if you agree.

I would be very happy if you could contribute.
I believe we should first consider the optimal testing methods for pypipe. What kind of tests are you thinking about?
