### ISSUE TITLE
 Github Action 'Publish package to PyPI' Failed

### ISSUE THREAD

**Issue by bugen** [bugen/pypipe#17]
@diazona I released v0.3.0a0 for PyPI release testing, but the Github Action 'Publish package to PyPI' failed. The 'Run tests' step encountered an error and failed. It appears that no tests were found. While there were no errors, a message indicating that there are no Python files during the ruff check was also output.

![image](https://github.com/bugen/pypipe/assets/7147107/5c21f7e4-41a5-478a-a7bf-c16eacda35a0)

 It is suspected that the current directory during execution is not in the project's root directory. Do you have any insights on this?

**Comment by diazona** [comment]
Ohh, I think I know: I forgot to include a step to check out the package when running tests. Without that there are no tests to run 😛

It should be an easy fix, just adding an `actions/checkout` step as part of the test job. I should have time to make a pull request with a fix later today, or feel free to do it yourself if you want.

Sorry for the inconvenience!

**Comment by bugen** [comment]
No problem at all. Thank you for the prompt response. 
I understand. To confirm, the fix is as simple as adding the following line to the "steps" section, right?
```
- uses: actions/checkout@v3
```
If so, I will fix it myself.

**Comment by diazona** [comment]
You'll need that line, and now that I look at it, I think you might need a `setup-python` line as well. I actually just started taking a look at it and here is the patch I had come up with:

```patch
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
index d748552..17e2319 100644
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -31,6 +31,9 @@ jobs:
     needs:
     - build
     steps:
+    - uses: actions/checkout@v3
+    - name: Set up Python
+      uses: actions/setup-python@v4
     - name: Download package
       uses: actions/download-artifact@v3
       with:
```

But this is not tested, so I don't know if anything else is needed.

Feel free to keep working on this yourself :+1:

**Comment by bugen** [comment]
Thanks for the comment. Well, I didn't want to inconvenience you, so I intended to fix it myself, but it seems that my knowledge of GitHub Actions is still lacking. Could you please send the PR? There's no rush, so take your time.

**Comment by diazona** [comment]
No problem! It's really no inconvenience at all; this is a very easy PR to prepare, once I got a few minutes to sit down and make it.

By the way, after thinking about it further, I think the `setup-python` step might not really be necessary now, but I believe it will be useful in the future if you expand the tests to cover more Python versions beyond just the default one. So I added it anyway.
