### ISSUE TITLE
Failed to release v.0.4.0

### ISSUE THREAD

**Issue by bugen** [bugen/pypipe#32]
The release of v0.4.0 has failed.
https://github.com/bugen/pypipe/actions/runs/7182600141

**Comment by bugen** [comment]
Until version 1.18.0, hatchling did not throw an error when there were no files matching the default file selection, as it automatically included *.py in such cases. However, starting from v1.19.0, an error occurs if there are no files matching the default file selection options unless you explicitly specify the files to include in the wheel.

- https://github.com/pypa/hatch/releases/tag/hatchling-v1.19.0
- https://github.com/pypa/hatch/commit/350ca032310a38aa47cfcd1c015f6f345fa3db85

For information about the default file selection:
- https://hatch.pypa.io/latest/plugins/builder/wheel/#default-file-selection

I confirmed that the build passes by adding the following settings to pyproject.toml:

```toml
[tool.hatch.build.targets.wheel]
packages = ["pypipe.py"]
```

**Comment by bugen** [comment]
@diazona Could you review the changes?

> I confirmed that the build passes by adding the following settings to `pyproject.toml`:
> 
> ```toml
> [tool.hatch.build.targets.wheel]
> packages = ["pypipe.py"]
> ```
Is it okay with just this change? If there are any additional modifications needed, could you please send a pull request?

**Comment by diazona** [comment]
Sure, I'll take a look at this when I have time, later today or tomorrow. I'll comment again here.

**Comment by diazona** [comment]
I checked over the documentation of hatch, and I believe you're right that this is the only change necessary. :+1:

Or, another alternative would be to restrict the version of hatchling used to build this project to 0.18 or earlier. But that wouldn't be as good of a solution.

**Comment by bugen** [comment]
@diazona Thank you for the review. 
> Or, another alternative would be to restrict the version of hatchling used to build this project to 1.18 or earlier. But that wouldn't be as good of a solution, for obvious reasons

I also don't think it's a good idea to restrict the version unless there are special reasons.
I will apply the fixes and proceed with the release.
