### ISSUE TITLE
Support standard installation

### ISSUE THREAD

**Issue by diazona** [bugen/pypipe#4]
Would you be open to making this installable with standard tools like `pip`, `pipx`, etc.? For a tool like this I'd really like to be able to install it using `pipx install pypipe`.

In addition to adding a small amount of metadata, this would also require uploading the package to PyPI (which involves setting up an account on PyPI and so on).

If you're interested, I'd be happy to send a PR for the relevant metadata changes.

**Comment by aresbit** [comment]
go ahead

**Comment by bugen** [comment]
Installing pypipe is easy, but it seems that many users would prefer managing it with a standard package management tool. Supporting installation with pipx is a good idea. Please do submit a pull request. However, there is one issue; please take a look at #6.

**Comment by diazona** [comment]
Understood! I'll try to accompany my pull request with clear instructions for everything else that needs to be done. (which means it may take me a little longer, it's no trouble though) And I will be happy to answer questions to the best of my ability.
