### ISSUE TITLE
Input mode questions (maybe requests?)

### ISSUE THREAD

**Issue by gwerbin** [bugen/pypipe#7]
Thanks for this tool! I had worked on something very similar years ago after my dissatisfaction with [Mario](https://pypi.org/project/mario/) and I'm happy to see that someone else was able to move the idea to completion.

I am curious about the currently-supported input modes. Specifically I am interested in:

* Parsing fixed-width tables, where each field is delimited by being a consistent number of text cells in length, rather than by a specific delimiter character. Fixed-width tables appear very often in the output of shell commands.
* AWK-like delimiter handling, e.g. by support a regex as delimiter, like `\s+`.

Are either of these currently supported? If not, is the author open to contributions? The latter could be added as an extension to the `-d` option, e.g. wrapping in `//` to indicate a regex pattern rather than a string literal, as in `-d '/\s+/`. The former could be added as a separate mode, or could be bundled as a "contributed" custom mode.

**Comment by bugen** [comment]
Thank you for your comment.

Parsing fixed-width tables and regular expression-based delimiter handling are indeed valuable features. Currently, pypipe does not support either of these, but there is a pull request (#3) for regular expression-based delimiter handling, and it should be implemented soon.

> Are either of these currently supported? If not, is the author open to contributions? 

Contributions are very welcome, but we have plans to address regular expression-based delimiter handling in PR #3 (I recommend your idea of extending `-d` option). What about fixed-width tables? The modifications for fixed-width tables overlap significantly with those for regular expression-based handling, so we'd prefer to wait for the implementation of regular expression-based handling. Alternatively, if you create a custom command for fixed-width tables, I am happy to include it as an example in the README.

**Comment by bugen** [comment]
Implementing parsing for Fixed-width tables can be quite challenging. There is a possibility of line breaks as well as the inclusion of borders. 

This is an extremely difficult-to-parse example.
```
$ lxc list
+------------------+---------+------------------------------+------+-----------+-----------+
|       NAME       |  STATE  |             IPV4             | IPV6 |   TYPE    | SNAPSHOTS |
+------------------+---------+------------------------------+------+-----------+-----------+
| server01         | RUNNING | 192.168.1.228 (eth0)         |      | CONTAINER | 0         |
+------------------+---------+------------------------------+------+-----------+-----------+
| server02         | RUNNING | 192.168.1.229 (eth0)         |      | CONTAINER | 0         |
+------------------+---------+------------------------------+------+-----------+-----------+
| server03         | RUNNING | 192.168.1.71 (eth0)          |      | CONTAINER | 0         |
|                  |         | 172.18.0.1 (br-ecf4e68eb72b) |      |           |           |
|                  |         | 172.17.0.1 (docker0)         |      |           |           |
+------------------+---------+------------------------------+------+-----------+-----------+
```
In this day and age, it might be a good idea to utilize the power of AI to convert them into other formats.

Even if we are working with pypipe, it seems better to limit the format to one that doesn't include line breaks and borders, like the output of the 'ps' command.

**Comment by gwerbin** [comment]
Thanks for the reply! I agree that fixed-width tables like those emitted by `ps` are consistently a serious challenge to parse, although in the particular example you provide, the `-` and `|` characters provide a way to cheat.

For many uses, extending `-d` to support regex I think is good enough to at least achieve feature parity with AWK, Perl, and the `read` shell builtin, which I think is a great place to be.

I don't know if I like the idea of bringing AI _unconditionally_ into this, but maybe there can be an `--auto` option that attempts to figure it out. That would be a great side project for someone, but it's definitely out of scope for this request.

In any case, it sounds like PR #3 covers enough of what I want that I'm satisfied. Thanks again for your thorough reply and for succeeding at building the thing I long since gave up on finishing.
